language: node_js
node_js:
  - '8'
install:
  - git clone --depth=50 --branch=feature/integration_tests git@github.com:dashevo/mn-bootstrap.git $TRAVIS_BUILD_DIR/mn-bootstrap
  - npm install
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - npm run lint
env:
  - MOZ_HEADLESS=1
addons:
  firefox: "latest"
