language: node_js
node_js:
  - '8'

services:
  - docker

addons:
  firefox: "latest"
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_COMPOSE_VERSION: 1.18.0

install:
  - pip install awscli --upgrade --user
  - pwd
  - cd ..
  - git clone --depth=50 --branch=feature/integration_tests git@github.com:dashevo/mn-bootstrap.git mn-bootstrap
  - cd mn-bootstrap
  - . ./.env
  - $(~/.local/bin/aws ecr get-login --no-include-email)
  - cd ../dapi-sdk
  - npm install
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - npm run lint
env:
  - MOZ_HEADLESS=1

